### PR TITLE
Add Message .Clone()

### PR DESCRIPTION
**Pull request by Dakinola892**
This is a basic implementation of a method used to clone a Message - it creates a new basic message, sets the spec from the given message and populates the new message with the packed message bytes from the given message. 

This should prove useful for constructing response messages which share the majority of fields with their requests. The necessary fields of the cloned requests can be altered to form a response.

### CODE REVIEW

**Review by wadearnold — APPROVED** [review]
This is great.

**Review by wadearnold — CHANGES_REQUESTED** [review]
I get a panic when running the test cases

**Comment by alovak** [comment]
@Dakinola892 thanks for the PR!

I think that this is a great start for the `Clone` method. I see `Clone` method has to clone everything inside the message. While spec can be re-used (we do not modify it), the message fields and other internal things should be copied in a similar way that is implemented here: https://github.com/barkimedes/go-deepcopy

There are some areas we have to pay attention to:
* Data - we link message fields with struct fields. It means that if we just copy pointers, changing data in cloned message will change the data in the original message.
* message fields that store slices - we need to re-create slice and copy data from one slice to a new one
* we have to clone bitmap
* properly clone composite fields
* ...

what do you think about it all?

**Comment by alovak** [comment]
@Dakinola892 I was thinking about something like https://github.com/barkimedes/go-deepcopy but your approach is simpler and it works! Thanks for the contributions!

**Comment by Dakinola892** [comment]
Unfortunately, i think I missed something when initially running the tests because I've been looking into it further and my implementation attempt is a bit to naive. Handling the deep copies of the all the fields is a challenge, especially dealing with composites since extracting the custom structs used to populate them isn't the simplest.

I wouldn't be against using go-deepcopy as an easier avenue if there is no pushback with relying on a 3rd-party library

**Comment by Dakinola892** [comment]
@alovak I experimented with go-deepcopy, and it doesn't seem to be able to handle composite fields (attempting to deepcopy.Anything() times out after reaching max depth of pointer loop), so I tried to fix my current implementation. 

These new changes creates allow .Clone() to return a new message that has an identical spec, bitmap and field values, however it is not completely identical to the original method. The cloned messages' fields do not have a data value or spec in the Field itself. Currently .Clone() will return identical messages for messages initially populated via .Unpack() or .UnmarshalJSON() (since the fields in the original also don't have spec & data fields populated), but not for those populated via SetData() with a populated Data struct.

I'm curious on your opinion if this matters or not, as the usecase for a .Clone() function is mostly to have an identical, mutable object with identical accessible field values, and I believe these changes accomplish that, so it may not be necessary to further pursue a perfect copy of messages.

**Comment by vtolstov** [comment]
i'm not sure... but why to encode to buffer prev message and decode bytes from buffer to new message ?
this creates new copy of message..

**Comment by alovak** [comment]
@vtolstov not sure I understand your question. Do you agree that it is enough to pack/unpack to clone a message? Or you have other ideas?

**Comment by vtolstov** [comment]
> @vtolstov not sure I understand your question. Do you agree that it is enough to pack/unpack to clone a message? Or you have other ideas?

yes, pack/unpack will create new message without pain via reflect and other stuff. So i think that internally pack/unpack will be good

**Comment by Dakinola892** [comment]
That’s the idea – the reflect package is only used to set a blank struct using .SetData() so the values can be access via the typed API, but the Fields won’t have their own spec or data values, only Value (or equivalent for Composites). From: Vasiliy TolstovSent: 02 December 2021 22:34To: moov-io/iso8583Cc: Daniel Akinola; MentionSubject: Re: [moov-io/iso8583] Add Message .Clone() (PR ***@***.*** not sure I understand your question. Do you agree that it is enough to pack/unpack to clone a message? Or you have other ideas?yes, pack/unpack will create new message without pain via reflect and other stuff. So i think that internally pack/unpack will be good—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Review by wadearnold — APPROVED** [review]

**Review by adamdecaf — APPROVED** [review]

**Comment by adamdecaf** [comment]
I'm looking for an approval from @alovak before we merge.

**Review by alovak — APPROVED** [review]
Let's try this out!

**Pull request merged**
