### PR TITLE
field: nil check Numeric, String, Composite, etc accessors

### PR DESCRIPTION
**Pull request by adamdecaf**
Issue: https://github.com/moov-io/iso8583/issues/195

### CODE REVIEW

**Review by alovak — APPROVED** [review]

**Comment by alovak** [comment]
This is a really good change to make code simpler for the callers

**Comment by adamdecaf** [comment]
@alovak Cool. I can add this to every field type.

**Comment by alovak** [comment]
thanks @adamdecaf! this PR looks 💪

the only thing that (kind of) worries me is that **Get**Value. On `message` we have `GetString()`, `GetBytes()`. But on `field` we have `String()` and `Bytes()` and now we add `GetValue()`.

We can introduce a breaking change by adding `Value()` and `SetValue()` and renaming `Value` into `value`. It will make code more consistent and safe. In my personal opinion, such change is just find/replace so it should not be a PITA.

thoughts?

**Comment by adamdecaf** [comment]
Yea I agree that `GetValue()` isn't idea and I'm okay with that breaking change. It's minor enough and increases runtime safety.

**Comment by adamdecaf** [comment]
@alovak feel free to merge this whenever you want. I know there are other 8583 changes in flight.

**Pull request merged**
