### PR TITLE
way4 initial changes

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by vtolstov** [comment]
this is not pass tests but works for way4 bcd coding
now my question - what is the proper way to fix this - pass to encoding.Decode func needed len (in case of L/LL/LL pass decoded len) or in another way?

**Comment by vtolstov** [comment]
@alovak  ?

**Comment by alovak** [comment]
This is how you mix length (`Pref`) and encoding:
```go
field.NewString(&field.Spec{
	Length:      19,
	Description: "Primary Account Number",
	Enc:         encoding.ASCII,
	Pref:        prefix.ASCII.LL,
})
```

if you want L or LL or LLL you have to use proper prefix. Also, prefix encodes length differently (ASCII, hex, binary, etc.)

**Comment by vtolstov** [comment]
```
2: field.NewNumeric(&field.Spec{                 
  Length:      19,                               
  Description: "F2: Primary Account Number",     
  Enc:         encoding.BCD,                     
  Pref:        prefix.BCD.L,                     
}),                                              
```

**Comment by vtolstov** [comment]
this is how decoding works and how it defined in way4 spec

**Comment by alovak** [comment]
@vtolstov it's invaluable to get PRs based on real life usage! Thanks a lot!

What was the issue with way4 bcd? Maybe we should update our test? Currently, it's not clear to me what the issue is.

How can we make it work together?

**Comment by vtolstov** [comment]
with you commit to fix odd number bytes you break decoding because len(dst)-length can gave negative number and in my case try to return slice with negative start offset

**Comment by alovak** [comment]
It would be great if you can share your example. Something like this:
* input => expected output

**Comment by vtolstov** [comment]
no prob
initial data
```
  data = []byte{ 
48, 49, 50, 48, 242, 60, 102, 129, 14, 227, 128, 0, 0, 0, 0, 0, 0, 1, 0, 0, 22, 71, 134, 116, 0, 0, 57, 83, 83, 0, 0, 0, 0, 0, 0, 1, 35, 0, 5,     25, 2, 82, 73, 0, 0, 85, 8, 82, 72, 5, 25, 35, 3, 81, 105, 3, 152, 0, 113, 0, 1, 0, 6, 1, 1, 1, 49, 49, 51, 57, 56, 53, 49, 49, 51, 52, 57, 55,        55, 54, 56, 50, 48, 50, 48, 48, 50, 53, 48, 48, 49, 54, 56, 52, 50, 53, 48, 48, 49, 54, 56, 52, 32, 32, 32, 32, 32, 32, 32, 84, 79, 79, 32, 71,        82, 65, 78, 68, 32, 83, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 62, 65, 76, 77, 65, 84, 89, 32, 32, 32, 32, 32, 32, 32, 75, 90, 0, 70,     57, 48, 56, 48, 48, 50, 48, 53, 57, 49, 48, 48, 48, 49, 50, 57, 49, 51, 48, 48, 49, 50, 57, 49, 57, 48, 48, 49, 118, 57, 53, 54, 48, 49, 49, 48,       48, 49, 48, 48, 49, 48, 48, 48, 48, 51, 0, 55, 56, 51, 51, 48, 48, 53, 55, 50, 55, 48, 48, 56, 52, 49, 48, 50, 48, 75, 65, 90, 89, 66, 65, 69, 86,     65, 32, 68, 32, 50, 54, 52, 32, 79, 70, 32, 50, 3, 152, 0, 153, 240, 97, 202, 9, 84, 70, 67, 67, 52, 50, 54, 57, 56, 203, 9, 84, 50, 48, 50, 49,       48, 51, 50, 48, 205, 25, 84, 50, 48, 49, 49, 50, 54, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 49, 56, 50, 54, 49, 50, 206, 15, 84, 52, 55,      56, 54, 55, 52, 42, 42, 42, 42, 53, 51, 53, 51, 207, 2, 84, 49, 209, 2, 84, 49, 210, 4, 84, 51, 57, 56, 211, 2, 84, 48, 212, 2, 84, 48, 213, 7,        84, 48, 49, 48, 48, 48, 82,                
}
```

try to decode with this spec https://gist.github.com/a66302c0e49b2603afd8756fa108e3d8
it must decodec without errors and have pan 4786740000395353

**Comment by alovak** [comment]
Thanks! I'll check.

**Comment by vtolstov** [comment]
> @vtolstov it's invaluable to get PRs based on real life usage! Thanks a lot!
> 

no problem, i'm add more test data for way4 iso8583 and after that i'm add tieto iso8583 (tieto have ascii hex encoding)

**Comment by vtolstov** [comment]
mostly i think that we need to fix len passing to encoding.Decode func.
To decode data len we pass max len from spec, to decode field data we must pass len that decoded on the first step and not spec Length

**Comment by vtolstov** [comment]
@alovak hi, do you have time to check?

**Comment by alovak** [comment]
Here are my findings from your [spec](https://gist.githubusercontent.com/vtolstov/a66302c0e49b2603afd8756fa108e3d8/raw/852d78eb0edec654ce857b47d107c406a34ef360/spec.go) and data:

raw data:

```
48, 49, 50, 48, 242, 60, 102, 129, 14, 227, 128, 0, 0, 0, 0, 0, 0, 1, 0, 0, 22, 71, 134, 116, 0, 0, 57, 83, 83, 0, 0, 0, 0, 0, 0, 1, 35, 0, 5,     25, 2, 82, 73, 0, 0, 85, 8, 82, 72, 5, 25, 35, 3, 81, 105, 3, 152, 0, 113, 0, 1, 0, 6, 1, 1, 1, 49, 49, 51, 57, 56, 53, 49, 49, 51, 52, 57, 55,        55, 54, 56, 50, 48, 50, 48, 48, 50, 53, 48, 48, 49, 54, 56, 52, 50, 53, 48, 48, 49, 54, 56, 52, 32, 32, 32, 32, 32, 32, 32, 84, 79, 79, 32, 71,        82, 65, 78, 68, 32, 83, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 62, 65, 76, 77, 65, 84, 89, 32, 32, 32, 32, 32, 32, 32, 75, 90, 0, 70,     57, 48, 56, 48, 48, 50, 48, 53, 57, 49, 48, 48, 48, 49, 50, 57, 49, 51, 48, 48, 49, 50, 57, 49, 57, 48, 48, 49, 118, 57, 53, 54, 48, 49, 49, 48,       48, 49, 48, 48, 49, 48, 48, 48, 48, 51, 0, 55, 56, 51, 51, 48, 48, 53, 55, 50, 55, 48, 48, 56, 52, 49, 48, 50, 48, 75, 65, 90, 89, 66, 65, 69, 86,     65, 32, 68, 32, 50, 54, 52, 32, 79, 70, 32, 50, 3, 152, 0, 153, 240, 97, 202, 9, 84, 70, 67, 67, 52, 50, 54, 57, 56, 203, 9, 84, 50, 48, 50, 49,       48, 51, 50, 48, 205, 25, 84, 50, 48, 49, 49, 50, 54, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 49, 56, 50, 54, 49, 50, 206, 15, 84, 52, 55,      56, 54, 55, 52, 42, 42, 42, 42, 53, 51, 53, 51, 207, 2, 84, 49, 209, 2, 84, 49, 210, 4, 84, 51, 57, 56, 211, 2, 84, 48, 212, 2, 84, 48, 213, 7,        84, 48, 49, 48, 48, 48, 82,                
```
**Field 0**
The first 4 bytes (ASCII) are MTI: `0120`

**Field 1**
We have a bitmap (binary). In your spec, you specify that it's 8 bytes. Our package ignores length and decodes bitmap in a dynamic manner. If the first bit of the first bitmap is set, then we have and read 2 bitmaps and so on. Decoded bitmap (in a binary representation):
```
11110010 00111100 01100110 10000001 00001110 11100011 10000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 00000000 00000000
```

**Field 2**
PAN. In your spec, it says that the max length is 19 (two digits), but the prefix is only one `L`. It should be `prefix.BCD.LL`.
Byte `22` is `0x16` (HEX). So, the length of the PAN is 16. Because you specify that data is in BCD encoding, we have to take the next 8 bytes to get the card number. Bytes: ` 71, 134, 116, 0, 0, 57, 83, 83` which, when converted to hex is: `4786740000395353`

...and our BCD prefix and decoder fail to decode it properly. It decodes it without panic when the prefix is specified as `LL`, but the result is wrong.

It will take a few days to understand where the issue is and fix it. It takes time to understand how BCD encoding works (with length) every time I get back to the package...

**Comment by vtolstov** [comment]
thanks, i know about LL, but this portion from way4 spec:
```
DE02
Primary Account Number (PAN)
HLVAR
n
7..19
BCD
Standard BCD coding assumes leading 0 in the first position for odd number of coded data positions.
This information is confidential and must be used exclusively to work with OpenWay software. It may not be duplicated, published or disclosed

PAN is a series of digits used to identify a customer account or relationship.
This is a card account number of up to 19 numeric digits. The length specifies
the number of digits in the account number.

HLVAR – The first byte of the field contains the length of the variable data
element that follows. The length is in the BCD coding. The length of the field
is expressed in data positions. It is not always in bytes. See "Field Length". For
example, the hex string 0x"06123456" contains a field of length 6 with the
"123456" value in the BCD coding.
```

**Comment by vtolstov** [comment]
so LVAR is proper thing for this, because len encoded in single byte

**Comment by vtolstov** [comment]
gentle ping

**Comment by alovak** [comment]
Hey! Here are my findings:

1. this field can't be L it's LL. Most probably it's a typo in your spec. Or this is how they understand the spec...
L, LL, etc. describes the length of the field, not how many bytes it's needed to store the length.

I looked in many places to double-check it (except all specs I have under my hand):
* OpenWay spec described [here](https://github.com/juks/iso-8583-socket-queue/blob/master/lib/iso8583/lib/packager/openWay.js#L155)  =>  ll-bin-hn
* [jPOS spec](https://github.com/jpos/jPOS/blob/master/jpos/src/main/java/org/jpos/iso/packager/ISO87APackager.java#L36) (one of many): IFA_LLNUM 
* https://en.wikipedia.org/wiki/ISO_8583#Examples_3 - you can see that PAN has n..19 which is LL.

2. I'm checking the data encoding. Length prefix now is binary. Our BCD length prefix accepts ASCII encoded data. That's why it returns the wrong length. I'm working on the fix currently.

**Comment by vtolstov** [comment]
I think that you right. I dont saw any specs that says about bytes needed to store, all specs says about number of digits.
May be all openway way4 specs must be treated  L as LL.

**Comment by vtolstov** [comment]
@alovak what you progress? may i can help you?

**Comment by vtolstov** [comment]
@alovak hi, what about fix to decode len?

**Comment by alovak** [comment]
@vtolstov sorry for the delay, may I ask you to look at this [PR](https://github.com/moov-io/iso8583/pull/61) and test it against the data you have and let me know the results?

I updated a lot of things and it does not fail for your spec and returns correct PAN. I hope that the rest of the data is correct as well :)

**Comment by vtolstov** [comment]
@alovak no problem, i'm try to test it today

**Comment by vtolstov** [comment]
superseded by https://github.com/moov-io/iso8583/pull/61

**Pull request closed without merging**
